apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sidekiq-development
  namespace: argocd
spec:
  destination:
    namespace: tla-development
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sidekiq-development-helm
    repoURL: >-
      http://nexus-nexus-repository-manager.nexus.svc.cluster.local:8081/repository/tla/
    targetRevision: '>= 1.0.0-0'
  syncPolicy:
    automated: {}
