apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persistent-volume-{{ .Values.environment }}-{{ .Values.appName }}
spec:
  mountOptions:
    - iam
  capacity:
    storage: {{ .Values.efsSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsId }}
