name: Update `.env` files
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: dotenv

      - name: Overwrite `.env` files and push
        run: |-
          cat <<EOS > api/.env
          AWS_REGION='${{ secrets.AWS_REGION }}'
          AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}'
          AIRBRAKE_PROJECT_ID='${{ secrets.AIRBRAKE_PROJECT_ID }}'
          AIRBRAKE_PROJECT_API_KEY='${{ secrets.AIRBRAKE_PROJECT_API_KEY }}'
          ELASTICSEARCH_CLOUD_ID='${{ secrets.ELASTICSEARCH_CLOUD_ID }}'
          ELASTICSEARCH_CLOUD_USER='${{ secrets.ELASTICSEARCH_CLOUD_USER }}'
          ELASTICSEARCH_CLOUD_PASSWORD='${{ secrets.ELASTICSEARCH_CLOUD_PASSWORD }}'
          EOS

          cat <<EOS > chatty/.env
          DEV_APP_PORT = "9999"
          DEV_JWT_SECRET = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
          DEV_MAX_REQ_SIZE = "50mb"
          EOS

          git config --global user.email "bovik+@cs.cmu.edu"
          git config --global user.name "Harry Bovik"
          git add -u
          git commit --amend -m "Update `.env` files"
          git push --force
